[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/forge'
cache_path  = 'cache_forge'
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src",
    "@chainlink/=node_modules/@chainlink/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@gelatonetwork/=node_modules/@gelatonetwork/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/=node_modules/@uniswap/",
    "@axelar-network/=node_modules/@axelar-network/",
    "base64-sol/=node_modules/base64-sol/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=node_modules/forge-std/",
    "lib/forge-std:ds-test/=lib/forge-std/lib/ds-test/src/",
]
deny_warnings = true


[profile.gas-optimize]
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200_000_000
via_ir = true

[profile.gas-optimize.optimizer_details]
inliner = true
deduplicate = true
constantOptimizer = true
yul = true # makes it worse
# orderLiterals = true # makes it worse
# cse = true # makes it worse

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
